# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmallGoose' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	pod 'AFNetworking', '~> 3.0'
#    pod 'SSZipArchive'

  # Pods for SmallGoose

  target 'SmallGoose-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmallGooseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
